### ISSUE TITLE
Investigating data from other APIs which we could use to give additional functionality to the application (so Spoonacular can work for us on both the restaurant menu items and the recipes)

### ISSUE THREAD

**Issue by kwubbenhorst** [kwubbenhorst/kitchen-elevation#17]
USER STORY: As a user, even though my main purpose in visiting the app is to elevate my home-cooking game with real menu suggestions and actual recipes, I may want to see facts related to nutrition in general or quotes about food and drink, food history facts, wine pairings etc., since I am a person, who, generally speaking, is interested in food.

ACCEPTANCE CRITERIA:
-- It is done when I have investigated other APIs that provide data which may be complementary to the main purpose of the site. (From the developer's perspective. It would be nice to be able to use Spoonacular for the menu items as well as the recipes since all other options for getting menu items are paid APIs. The client wants 2 APIs used, so casting around for another API we can put to some purpose is mostly just to satisfy this client-insistence). 
--It is done when I have thought of a way to integrate this complementary feature non intrusively in the application's flow. Agile consultation should probably occur before coding the feature, but if agreed to include it, the coding responsibility may come back here.

**Comment by AllanYuen** [comment]
Managed to discover a working API with The Cocktail DB to support the secondary API to be used in this project.  Successfully tested to confirm data return from API request call.

**Comment by AllanYuen** [comment]
Rendered JSON data from the Cocktail DB API call to pull in relevant cocktail drink details into the app.  Next step is to work on displaying content into a button triggered modal.

**Comment by AllanYuen** [comment]
Completed the development of a functional random drink search call to secondary API call to the Cocktail DB and have incorporated it into the Search2.html file.
