### ISSUE TITLE
Dividing up the presentation

### ISSUE THREAD

**Issue by kwubbenhorst** [kwubbenhorst/kitchen-elevation#26]
USER STORY: As a user I am interested in hearing the developers pitch the reason they thought the app would be useful, explain the various decisions they made in development, hear plans for further iterations and generally have my input in keeping with the model of agile software development.

ACCEPTANCE CRITERIA: 
-- It is done when a project presentation is developed in which all collaborators have some speaking opportunity.
-- It is done when a project presentation slideshow is made following this presentation template:
1. Slide show with project title
2. Elevator Pitch
3. Concept (description, motivation for development, user story)
4. Process (technologies used, breakdown of tasks and roles, challenges, successes)
5. Demo
6. Directions for Future Development
7. Links (deployed application, github repo)
(The template is from Mark Alifano, an EdX Bootcamp assistant instructor)

**Comment by AllanYuen** [comment]
- Reviewed with the group to agree to a desired logo to use for the project
- Aligned presentation topics to provided template
- Divvied up the presentation to all speakers
- Final review and dry-run scheduled for November 19, 2023 @ 1pm (ET)
